// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"パラメータ解析を提供する共通基盤です","parameters":{}},
{"name":"messageskip","status":true,"description":"メッセージスキッププラグイン","parameters":{"スキップキー":"S","オートキー":"A","スキップスイッチ":"0","オートスイッチ":"0","スキップアイコン":"140","オートアイコン":"75","アイコンX":"0","アイコンY":"0","押し続けスキップ":"true","ピクチャは押し続け対象外":"true","オート待機フレーム":"100 + textSize * 10","終了解除スイッチID":"0","スキップピクチャ":"","スキップピクチャX":"500","スキップピクチャY":"0","オートピクチャ":"","オートピクチャX":"750","オートピクチャY":"0","スイッチピクチャ":"","スイッチピクチャトリガー":"0","スイッチピクチャX":"750","スイッチピクチャY":"0","ボタン原点":"0","ボタン表示スイッチID":"0","ピクチャ座標タイプ":"relative","無効化スイッチ":"0","skipWait":"false"}},
{"name":"TextPicture","status":true,"description":"テキストをピクチャとして表示します。","parameters":{}},
{"name":"AnotherNewGame","status":true,"description":"アナザーニューゲーム追加プラグイン","parameters":{"anotherDataList":"[\"{\\\"name\\\":\\\"回想のスキマ\\\",\\\"mapId\\\":\\\"7\\\",\\\"mapX\\\":\\\"11\\\",\\\"mapY\\\":\\\"7\\\",\\\"hidden\\\":\\\"false\\\",\\\"disable\\\":\\\"false\\\",\\\"addPosition\\\":\\\"0\\\",\\\"demoWaitFrame\\\":\\\"0\\\",\\\"switchId\\\":\\\"0\\\",\\\"fileLoad\\\":\\\"false\\\",\\\"noFadeout\\\":\\\"false\\\"}\"]","defaultCursorIndex":"0"}},
{"name":"DarkPlasma_SharedSwitchVariable","status":true,"description":"全てのセーブデータで共有するスイッチ・変数を指定する","parameters":{"switchRangeList":"[]","variableRangeList":"[]"}},
{"name":"HIME_LargeChoices","status":true,"description":"v1.2 複数の'選択肢の表示…'を1つの大きなリストに結合します","parameters":{}},
{"name":"LL_TrackNameWindow","status":true,"description":"BGM切替時に曲名を表示します。","parameters":{"trackLists":"[\"{\\\"trackFile\\\":\\\"フィールド/破滅スパーク -恋色マスタースパークアレンジ- by ajapaのBGM\\\",\\\"trackName\\\":\\\"♪破滅スパーク（原曲：恋色マスタースパーク） 『by ajapaのBGM』\\\"}\",\"{\\\"trackFile\\\":\\\"『おてんば恋娘』　byえもん\\\",\\\"trackName\\\":\\\"『おてんば恋娘』　byえもん\\\"}\",\"{\\\"trackFile\\\":\\\"その他BGM/今昔幻想郷～ Flower Land　\\\",\\\"trackName\\\":\\\"『今昔幻想郷～Flower Land』アレンジ　bySABA\\\"}\",\"{\\\"trackFile\\\":\\\"紅魔館BGM/上海紅茶館～らんちたいむ～\\\",\\\"trackName\\\":\\\"上海紅茶館～らんちたいむ～　byえるでぃ\\\"}\",\"{\\\"trackFile\\\":\\\"不知夜月（月時計～ルナ・ダイアル）\\\",\\\"trackName\\\":\\\"不知夜月（月時計～ルナ・ダイアル）bySABA\\\"}\",\"{\\\"trackFile\\\":\\\"魔理沙BGM/しっとりマスタースパーク　ざわぴー\\\",\\\"trackName\\\":\\\"しっとりマスタースパーク　byざわぴー\\\"}\"]","twX":"700","twY":"50","twWidth":"300","twTransition":"3","twShowCount":"150","twOriginalBg":"","twTextColor":"#ffffff","twTextBorder":"rgba(0, 0, 0, 0.6)","optionCommandName":"曲名表示"}},
{"name":"CenteredMapName","status":false,"description":"マップ名を画面の中央に表示します。","parameters":{}},
{"name":"Foreground","status":true,"description":"マップに合わせてスクロールする近景の設定(Ver1.0.1)","parameters":{}}
];
